name: Test Cron

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # 每 5 分钟，合法间隔

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 打印时间
        run: echo "Run at $(date -u)"
